import type { Metadata } from "next";
import "./globals.css";
import Cabecalho from "@/components/Cabecalho/Cabecalho";

export const metadata: Metadata = {
  title: "Mecar",
  description: "Generated by create next app",
};

export const viewport = {
  width:"device-width",
  initial_scale:1.0,
  colorScheme:"light"
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <Cabecalho/>
        {children}
      </body>
    </html>
  );
}
